config/routes.rb
Rails.application.routes.draw do

  root to: 'tweets#index'

  devise_for :users, :path_prefix => 'devise', controllers: {
    omniauth_callbacks: 'devise/users/omniauth_callbacks'
  }
  
  resources :tweets do
    collection do
      get 'search'
    end
  end
  
  resources :users, only: [:index, :show] do
    member do
      post 'alt_lock'
      get 'follower_list'
      get 'following_list'
    end
  end
  
  resources :user_configs, only: [:create]
  resources :reactions, only: [:create, :update]
  resources :relationships, only: [:create]
  
  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    belongs_to :user
    has_many :reactions, dependent: :destroy
    
    has_many :retweets, class_name: :Tweet, foreign_key: :retweet_id, dependent: :destroy #返信をretweetsで参照
    belongs_to :parent_tweet, class_name: Tweet, foreign_key: :retweet_id #返信元をparent_tweetで参照

    validates :user_id, presence: true
    validates :content, presence: true, length: {maximum: 140} #tweet内容は140文字制限

    scope :first_tweets, -> do    # オリジナルのTweet(返信ではないもの)だけを返すTweetモデルのscope
        where(retweet_id: nil)
    end
    scope :sort_by_created_date_with, -> (page_num) do
        page(page_num).per(10).order('created_at DESC')
    end

    def has_parent?  #リツイートかどうかを返す
        !self.retweet_id.nil?
    end

    def first_parent    #返信元をたどっていき､最初のツイートを返す(今回未使用)
        ch = self
        while ch.retweet_id.present?
            ch=Tweet.find(ch.retweet_id)
        end
        return ch
    end

    def has_emotion_by_user? (emotion, user_id)   #ツイートに対するUserのemotionがあればtrue / なければfalse
        return false unless r = Reaction.find_by(tweet_id: self.id, user_id: user_id)
        r.has_emotion?(emotion)
    end

    def has_any_reactions?   #ツイートに対するリアクションがあればtrue / なければfalse
        self.reactions.present?
    end

    def count_reactions   #あるツイートに対するリアクション数をハッシュで返す
        counter={}
        Reaction.emotions.each do |emotion, emotion_id|
            counter.store(emotion, self.reactions.where(:emotion, emotion).size)
        end
        return counter
    end

    def count_reactions_by_emotion_id (emotion_id)
        self.reactions.where('emotion=?', emotion_id).size
    end
    
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  include Common

  before_action :authenticate_user!  #ログインしていない場合はログイン画面に飛ばす
  before_action :find_tweet, only: [:show, :edit, :update, :destroy]  #params[:id]で指定されたTweetインスタンスをセットする
  before_action :init_emotions
  before_action :init_srch_query, only: [:index, :show, :edit, :search]  #検索窓用のサーチクエリをセットする
  
  def index
    @user_config = UserConfig.find_or_initialize_by(user_id: current_user.id)

    @tweets = Tweet.all.includes(:retweets, :user, :reactions).sort_by_created_date_with(params[:page])
    @first_tweets = @tweets.first_tweets
    # first_tweetsは､オリジナルのTweet(返信ではないもの)だけを返すTweetモデルのscope
    # 検索結果はsearchコントローラーで別に処理｡(返信も検索対象に含めて表示させたいので､処理を分けている)

    @tweet = Tweet.new
  end
  
  def search
    @tweets = @q.result.sort_by_created_date_with(params[:page])

    # サーチ結果から､さらにネストしたサーチはしない(indexからサーチかけた場合と同じ結果になる)
    # (重層サーチする場合は､init_srch_queryをカスタマイズ｡説明を入れないとユーザーが混乱させる可能性あり)
  end
  
  def edit
  end
  def show
    @new_retweet=Tweet.new
  end

  def update      #updateに関してはindex画面へ戻るため､ajaxなしとする
    @tweet.user_id = current_user.id
    @tweet.attributes = tweet_params
    if @tweet.save
      flash[:notice] = I18n.t('tweet.updated')
      redirect_to action: :index
    else
      flash.now[:alert] = @tweet.errors.full_messages
      init_srch_query
      render :edit
    end
  end

  def create
    @tweet = Tweet.new
    @tweet.user_id = current_user.id
    @tweet.attributes = tweet_params
    if @tweet.save
      respond_to do |format|
        format.html do
          redirect_to action: :index
        end
        format.json do
          new_html = render_to_string partial: 'partials/ajax_new_tweet', formats: :html, locals: {t: @tweet}
          render json: {result: 'success', html: new_html}
        end
      end
    else
      respond_to do |format|
        format.html do
          flash[:alert] = @tweet.errors.full_messages
          init_srch_query
          @user_config = UserConfig.find_or_initialize_by(user_id: current_user.id)
          @tweets = Tweet.all.includes(:retweets, :user, :reactions).sort_by_created_date_with(params[:page])
          @first_tweets = @tweets.first_tweets

          redirect_to :back
        end
        format.json do
          render json: {result: 'failure', error_message: @tweet.errors.full_messages}
        end
      end
    end
  end

  def destroy
    @tweet.destroy!
    flash[:notice] = I18n.t('tweet.deleted')
    redirect_to action: :index
  end

  private

  def tweet_params
    params.require(:tweet).permit(:content, :retweet_id)
  end
  def find_tweet
    @tweet = Tweet.find(params[:id])
  end
  def init_srch_query
    @q = Tweet.search(params[:q])
  end
  def init_emotions
    @emotions = Reaction.emotions
    @emotion_array = create_emotion_array
  end


end

app/helpers/tweets_helper.rb
module TweetsHelper
    def my_tweet? (tweet)
        tweet.user_id==current_user.id
    end
end

app/views/tweets/_per_tweet.html.erb
<% if t.present? %>

  <div class='per_tweet'>
    
    <div class='user_image'>
      <div class='prof-image-box'>
        <%= image_tag t.user.image_url, class: 'prof-image' %>
      </div>

      <div class='tweet_header'>

        <span class='user_name'>
          <%= t.user.name %>
        </span>

        <span class='tweeted_datetime'>
          <%= link_to tweet_path(id: t.id) do %>
            <%= t.created_at %>
          <% end %>
        </span>
      </div>

      <div class='tweet_content'>
        <% if t.user_id == current_user.id %>
          <%= link_to edit_tweet_path(id: t.id) do %>
            <%= t.content %>
          <% end %>
        <% else %>
            <%= t.content %>
        <% end %>
        
      </div>

    </div>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<%= render 'partials/header', srchpath: search_tweets_path %>

<div class='container-fluid'>

  <div class='row main-row'>
    <div class='col-sm-2'></div>
    <div class='col-sm-8 col-xs-12 main-container'>

      
      <%= render 'partials/alert' %>

      <div class="timeline">

        <% if @tweet.user.id == current_user.id %>
          <%= render 'partials/new_tweet', t: @tweet, reply_to: false, ajax_post: false, btn: '修正' %>
        <% elsif current_user.admin? %>
          <div class='tweet-container'>
            <%= render 'partials/render_one_tweet', t: @tweet %>
          </div>
        <% end %>
    
        <div class='tweet-del-btn'>
          <%= button_to 'つぶやきを削除', tweet_path(id: @tweet.id), method: :delete, class: 'btn btn-danger', data: {confirm: '削除していいですか？'} %>
        </div>

      </div>
    </div>
    <div class='col-sm-2'></div>
    
  </div>    
</div>    

app/views/tweets/index.html.erb
<%= render 'partials/header', srchpath: search_tweets_path %>

<div class='container-fluid'>

  <div class='row main-row'>
    <div class='col-sm-2'></div>
    <div class='col-sm-8 col-xs-12 main-container'>

      <%= render 'partials/alert' %>

      <div class='index-new-tweet'>
        <%= render 'partials/new_tweet', t: @tweet, reply_to: false, ajax_post: true, btn: '投稿' %>
      </div>

      <div class="timeline index">
      
        <%= render 'partials/config_options' %>
        
        <div class='tweet-box'>
          <% @first_tweets.each do |t| %>
            <div class='tweet-container'>
              <%= render 'partials/trace_tweets', t: t %>
            </div>
          <% end %>
        </div>
        
        <%= paginate @first_tweets %>
      </div>

    </div>
    <div class='col-sm-2'></div>
  </div>

</div>  

app/views/tweets/search.html.erb
<%= render 'partials/header', srchpath: search_tweets_path %>

<div class='container-fluid'>

  <div class='row main-row'>
    <div class='col-sm-2'></div>
    <div class='col-sm-8 col-xs-12 main-container'>

      <%= render 'partials/alert' %>

      <div class="timeline">
      
        <div class='tweet-container'>
          <% @tweets.each do |tweet| %>
            <%= render 'partials/render_one_tweet', t: tweet %>
          <% end %>
        </div>
        
        <%= paginate @tweets %>
      </div>

    </div>
    <div class='col-sm-2'></div>
  </div>

</div>  

app/views/tweets/show.html.erb
<%= render 'partials/header', srchpath: search_tweets_path %>

<div class='container-fluid'>

  <div class='row main-row'>
    <div class='col-sm-2'></div>
    <div class='col-sm-8 col-xs-12 main-container'>

      <%= render 'partials/alert' %>

      <div class="timeline">
        <div class='tweet-container'>
          <%= render 'partials/trace_tweets', t: @tweet %>
        </div>
      </div>

      <%= render 'partials/new_tweet', t: @new_retweet, reply_to: @tweet.id, ajax_post: false, btn: '返信' %>

    </div>
    <div class='col-sm-2'></div>
  </div>

</div>  