config/routes.rb
Rails.application.routes.draw do

  root to: 'tweets#index'

  devise_for :users, :path_prefix => 'devise', controllers: {
    omniauth_callbacks: 'devise/users/omniauth_callbacks'
  }
  
  resources :tweets do
    collection do
      get 'search'
    end
  end
  
  resources :users, only: [:index, :show] do
    member do
      post 'alt_lock'
      get 'follower_list'
      get 'following_list'
    end
  end
  
  resources :user_configs, only: [:create]
  resources :reactions, only: [:create, :update]
  resources :relationships, only: [:create]
  
  

end

app/views/partials/_ajax_new_tweet.html.erb
<!--新たなツイートを描画するajax用パーシャル-->

<!--パーシャル変数:-->

<!--パーシャル変数:-->
<!-- t･･描画したいデータが入った･Tweetインスタンス-->


<div class='tweet-container'>
  <%= render 'partials/render_one_tweet', t: t %>
</div>

app/views/partials/_alert.html.erb
<!--メッセージ･アラート機能-->

<div class='system-message-container'>
  
  <div id='notice'><%= notice if flash[:notice].present? %></div>
  
  <!--flash[:alert]は､ハッシュだけでなくdeviseから文字列でも渡されることもあるので､処理を分ける-->
  
  <div id='alert'>
  
  <% if flash[:alert].present? %>
    <% if flash[:alert].is_a?(String) %>
      <%= alert %>
    <% elsif flash[:alert].is_a?(Array) %>
      <% flash[:alert].each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
  <% end %>
  
  </div>

</div>

app/views/partials/_config_options.html.erb
<!--indexのタイムライン表示オプションを切り替えるためのボタン等-->


<div class='option-wrapper'>

  <div class='option-show-replies'>
    <%= label_tag 'show-replies-checkbox', '返信を全て表示' %>
    <%= check_box_tag 'show-replies-checkbox', true, @user_config.show_replies %>
  </div>

  <ul class="nav nav-tabs", id="option-show-followers-only">
    <li role="presentation" class="tab tab-all <%='active' if !@user_config.show_followers_only %>"><a href="#">すべて</a></li>
    <li role="presentation" class="tab tab-followers-only <%= 'active' if @user_config.show_followers_only %>"><a href="#">フォロー中</a></li>
  </ul>

</div>

app/views/partials/_header.html.erb
<!--ヘッダー(navbar)の作成-->

<!--パーシャル変数:-->
<!-- srchpath･･･検索クエリを返す先のactio名が入る､falseを入れた場合は検索画面を描画しない-->


<div id='header'>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
  
        <a class="navbar-brand header-logo-box" href=<%= root_path %>>
          <%= image_tag "/images/tweetie_logo_final.png", class: 'header-logo' %>
        </a>
  
        <button type="button" class="navbar-toggle collapsed navbar-right header-btn" data-toggle="collapse" data-target="#header-nav-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="header-nav-collapse">
          <ul class="nav navbar-nav header-links">
            <% if user_signed_in? %>
  
              <li><%= link_to "@#{current_user.name}", user_path(current_user.id), class: 'account-name' %></li>
              <% if current_user.admin? %>
                <li><%= link_to 'ユーザー管理', users_path, class: 'link link-1' %></li>
              <% else %>
                <li><%= link_to '設定変更', edit_user_registration_path, class: 'link link-1' %></li>
              <% end %>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'link link-2' %></li>
            <% else %>
              <li><%= link_to 'ログイン', new_user_session_path, class: 'link link-1' %></li>
              <li><%= link_to '新規登録', new_user_registration_path, class: 'link link-2' %></li>
            <% end %>
          </ul>
        </div>
  
        <% if user_signed_in? && srchpath %>
          <%= search_form_for @q, url: srchpath, method: :get, class:"navbar-form navbar-left search-area" do |f| %>
            <%= f.search_field :content_cont, class: 'search-box' %>
            <%= f.submit '検索', class: 'btn search-btn hidden-xs' %>
          <% end %>
        <% end %>
  
    </div>
  </nav>

</div>

app/views/partials/_new_tweet.html.erb
<!--ツイート入力画面を描画する-->

<!--パーシャル変数:-->

<!-- t･･･フォーム生成のためのベースとなるTweetインスタンス-->
<!--    (newならば新規インスタンス､editなら既存インスタンス)-->

<!-- reply_to･･･返信の場合､返信元のidが入る｡falseの場合は新規･既存ツイート(retweet_i上書きせず)-->
<!--ajax_post･･･trueの場合､ajax更新-->
<!--btn･･･ボタンに表示される文字(投稿､編集､返信)-->


<div class='new-tweet-container'>


  <% if ajax_post %>
    <%= form_for t, remote: true, format: :json, authenticity_token: true, html: {id: 'new-tweet-form'} do |f| %>
      <div class='form-group new-tweet-box'>
        <%= f.text_area :content, rows: '5', placeholder: '（140文字以内で投稿）', class: 'form-control new-tweet' %>
  
        <% if reply_to %>
          <%= f.hidden_field :retweet_id, value: reply_to %>
        <% end %>
  
      </div>
      <%= f.submit btn, class: 'btn submit-btn' %>
    <% end %>

  <% else %>

    <%= form_for t, html: {id: 'new-tweet-form'} do |f| %>
      <div class='form-group new-tweet-box'>
        <%= f.text_area :content, rows: '5', placeholder: '（140文字以内で投稿）', class: 'form-control new-tweet' %>
  
        <% if reply_to %>
          <%= f.hidden_field :retweet_id, value: reply_to %>
        <% end %>
  
      </div>
      <%= f.submit btn, class: 'btn submit-btn' %>
    <% end %>
  <% end %>
  
</div>

app/views/partials/_per_tweet.html.erb
<!--ツイート1つ分の描画-->

<!--パーシャル変数:-->
<!-- t･･描画したいデータが入った･Tweetインスタンス-->

<!-- tを親とする返信がぶら下がっている場合､再帰的に呼び出し描画する-->
<!-- ※ 現状は､古いもの順(idが小さいもの順)に表示されるが､変更する場合はeachの順序を変える-->

<div class='per-tweet row'>
  
  <div class='user-image col-xs-1'>
    <div class='prof-image-box'>
      <%= image_tag t.user.image_url, class: 'prof-image' %>
    </div>
  </div>

  <div class='user-tweet col-xs-11'>
    <div class='tweet-header'>

      <span class='user-name'>
        <%= link_to user_path(t.user.id) do %>
          @<%= t.user.name %>
        <% end %>
      </span>

      <span class='tweeted-datetime'>
        <%= link_to tweet_path(id: t.id) do %>
          ( <%= t.created_at.strftime("%Y-%m-%d %H:%M:%S") %> )
        <% end %>
      </span>
    </div>

    <div class='tweet-content'>
      <% if t.user_id == current_user.id %>
        <%= link_to edit_tweet_path(id: t.id) do %>
          <%= t.content %>
        <% end %>
      <% else %>
          <%= t.content %>
      <% end %>
      
    </div>
  </div>

</div>

<% t.retweets.each do |retweet| %>
  <div class='row'>
    <div class='col-xs-1'></div>
    <div class='col-xs-11'>
      <%= render 'partials/per_tweet', t: retweet %>
    </div>
  </div>
<% end %>

  

app/views/partials/_reaction_buttons.erb
<!--ツイートごとのリアクションボタンを表示-->
<!--t: 対象となるTweetオブジェクト-->

<% Reaction.emotions.each do |emotion, emotion_id| %>
  <% next if emotion == :na %>
  <% if t.has_emotion_by_user?(emotion, current_user.id) %>
      <% cls = class_by_emotion(emotion) + " emotion-icon selected" %>
  <% else %>
      <% cls = class_by_emotion(emotion) + " emotion-icon not-selected" %>
  <% end %>
  <%= link_to '', reactions_path(emotion: emotion, tweet_id: t.id, format: :json), remote: true, method: :post, class: cls %>
<% end %>

app/views/partials/_reaction_buttons.html.erb
<!--ツイートごとのリアクションボタンを表示-->
<!--t: 対象となるTweetオブジェクト-->

<% Reaction.emotions.each do |emotion, emotion_id| %>
  <% next if emotion == :na %>
  <% if t.has_emotion_by_user?(emotion, current_user.id) %>
      <% cls = class_by_emotion(emotion) + " emotion-icon selected" %>
  <% else %>
      <% cls = class_by_emotion(emotion) + " emotion-icon not-selected" %>
  <% end %>
  <%= link_to '', reactions_path(emotion: emotion, tweet_id: t.id, format: :json), remote: true, method: :post, class: cls %>
<% end %>

app/views/partials/_reaction_counter.html.erb
<!--ツイートごとのリアクションボタンを表示-->
<!--t: 対象となるTweetオブジェクト-->

<% @emotions.each do |emotion, emotion_id| %>
  <% next if emotion == :na %>

  <% ct = @emotion_array[emotion_id][t.id] %>
  <% unless ct==0 %>
      <div class = "<%= class_by_emotion(emotion) %>">
          <span class = "emotion-ctr-text"><%= ct %></span>
      </div>
  <% end %>

<% end %>

app/views/partials/_render_one_tweet.html.erb
<!--ツイート1つ分｢だけ｣を描画(再帰的にたどったりしない)-->

<!--パーシャル変数:-->
<!-- t･･描画したいデータが入った･Tweetインスタンス-->

<div class="per-tweet row <%= (my_tweet?(t) ? 'per-mine' : 'per-others') %> <%= (current_user.following?(t.user) ? 'followed' : 'not-followed') %>" >

  <div class='user-image col-xs-1'>
    <div class='prof-image-box'>
      <%= link_to user_path(t.user.id) do %>
        <%= image_tag t.user.image_url, class: 'prof-image' %>
      <% end %>
    </div>
  </div>
  
  <div class='user-tweet col-xs-11'>
    <div class='tweet-header'>
  
      <span class='user-name'>
        <%= link_to user_path(t.user.id) do %>
          @<%= t.user.name %>
        <% end %>
      </span>
  
      <span class='tweeted-datetime'>
        <%= link_to tweet_path(id: t.id) do %>
          ( <%= t.created_at.strftime("%Y-%m-%d %H:%M:%S") %> )
        <% end %>
      </span>

      <% if t.has_parent? %>
        <span class='retweeted_from'>
          <br class='visible-xs-inline'>
          <%= link_to tweet_path(id: t.parent_tweet.id) do %>
            <%= "@#{t.parent_tweet.user.name}への返信"%>
          <% end %>
        </span>
      <% end %>

    </div>
  
    <div class='tweet-content'>
      <% if t.user_id == current_user.id || current_user.admin? %>
        <%= link_to edit_tweet_path(id: t.id) do %>
          <%= t.content %>
        <% end %>
      <% else %>
        <%= link_to tweet_path(id: t.id) do %>
          <%= t.content %>
        <% end %>
      <% end %>
    </div>


    <div class='reaction-counter-container'>
      <%= render 'partials/reaction_counter', t: t %>
    </div>


    <section class="reaction-btn-modal reaction-btn-modal-<%= t.id %>" id="reaction-btn-modal-id-<%= t.id %>">
      <div class='reaction-buttons-container'>
        <%= render 'partials/reaction_buttons', t: t %>
      </div>
    </section>
  </div>
</div>

app/views/partials/_trace_tweets.html.erb
<!--ツイート描画 (対象ツイートから派生する返信を全て描画)-->

<!--パーシャル変数:-->
<!-- t･･描画したいデータが入った･Tweetインスタンス-->

<!-- tを親とする返信がぶら下がっている場合､再帰的に呼び出し描画する-->
<!-- ※ 現状は､古いもの順(idが小さいもの順)に表示されるが､変更する場合はeachの順序を変える-->


<%= render 'partials/render_one_tweet', t: t %>

<% if t.retweets.size>0 %>
  <div class='row retweet-content'>
    <div class='col-sm-1'></div>
    <div class='col-sm-11 retweet-box'>
      <div class='retweet-header'></div>

      <% t.retweets.each do |retweet| %>
        <div class='retweet-body'>
          <%= render 'partials/trace_tweets', t: retweet %>
        </div>
      <% end %>

    </div>
  </div>
<% end %>

app/views/partials/_user_account_info.html.erb
<!--ユーザープロファイル管理情報の表示(admin用)-->

<!--パーシャル変数:-->
<!-- u:描画するユーザーデータを保持したUserインスタンス-->



<div class='user-follow-status'>
  <%= link_to user_path(u.id) do %><%= u.tweets.size %><% end %>件のツイート　<br class='visible-xs-inline'>
  <%= link_to following_list_user_path(u.id) do %><%= u.following.size %><% end %>人をフォロー中　<br class='visible-xs-inline'>
  <%= link_to follower_list_user_path(u.id) do %><%= u.followers.size %><% end %>人のフォロワー
</div>

<% if current_user.admin? %>
  <span class='user-login-datetime'>
      最終ログイン日時：<br class='visible-xs-inline'>
      <%= u.current_sign_in_at.strftime("%Y-%m-%d %H:%M:%S") %><br />
  </span>
  <span class='user-login-datetime'>
      最終ログインIP：<br class='visible-xs-inline'>
      <%= u.last_sign_in_ip %><br />
  </span>
  <span class='user-login-datetime'>
      ログイン回数：<br class='visible-xs-inline'>
      <%= u.sign_in_count %><br />
  </span>
  <span class='user-login-datetime'>
      ロック状態：<br class='visible-xs-inline'>
      <%= u.access_locked? ? 'locked' : '-' %><br />
  </span>
<% end %>

app/views/partials/_user_profile.html.erb
<!--ユーザープロファイルの描画-->

<!--パーシャル変数:-->
<!-- u:描画するユーザーデータを保持したUserインスタンス-->

<div class='row user-profile'>
  
  <div class='user-image col-sm-3 col-xs-5'>
    <div class='prof-image-box'>
      <%= link_to user_path(u.id) do %>
        <%= image_tag u.image_url, class: 'prof-image' %>
      <% end %>
    </div>

    <div class='user_follow'>
      <% if u.id!=current_user.id %>
        <% if current_user.following?(u) %>
          <%= button_to "フォロー中", relationships_path(user_id: u.id), method: :post, class: "btn btn-warning" %>
        <% else %>
          <%= button_to "フォローする", relationships_path(user_id: u.id),  method: :post, class: "btn btn-info" %>
        <% end %>
      <% end %>
    </div>


  </div>

  <div class='user-prof col-sm-9 col-xs-7'>

    <div class='prof-header'>

      <span class='user-name'>
        <%= link_to user_path(u.id) do %>
          @<%= u.name %>
        <% end %>
        <% if u.admin? %>
          <span class='mark-admin'>ADMIN</span> 
        <% end %>
      </span>
      <% if current_user.admin? && !u.admin? %>
        <div class='user-lock-btn'>
          <% if u.access_locked? %>
            <%= button_to "ロック中", alt_lock_user_path(id: u.id), method: :post, class: "btn btn-danger" %>
          <% else %>
            <%= button_to "ロックする", alt_lock_user_path(id: u.id), method: :post, class: "btn btn-success" %>
          <% end %>
        </div>
      <% end %>

      <%= render 'partials/user_account_info', u: u %>

    </div>

      <div class='user-prof-text'>
        <div class='prof-title'>
          プロフィール
        </div>
        <div class='prof-body'>
          <%= u.profile %>
        </div>
      </div>

  </div>

</div>

  